### ISSUE TITLE
1D quadrotor not working

### ISSUE THREAD

**Issue by Wang4758** [utiasDSL/safe-control-gym#17]
Hi there,

Has anyone tested the code for 1D quadrotor? I've got multiple errors when I changed the `quad_type`.

**Comment by JacopoPan** [comment]
Hi @Wang4758,

can you add the command line you are trying to run and the terminal output?
Just changing `quad_type` might not work if the environment is trying to also load constraints/other parameters that are meant for the 2D experiments.

**Comment by Wang4758** [comment]
> Hi @Wang4758,
> 
> can you add the command line you are trying to run and the terminal output? Just changing `quad_type` might not work if the environment is trying to also load constraints/other parameters that are meant for the 2D experiments.

I changed the `quad_type` in `tracking.yaml` and ran `python tracking.py --overrides ./tracking.yaml`.

**Comment by JacopoPan** [comment]
@Wang4758 

I see. That is expected because that script (`tracking.py`) is specific to the 2D quad (e.g. it includes the drawing/visualization of a 2D trajectory, etc.). 

The simplest way run a 1D quad simulation, without control, is the `verbose_api.py` example:
- changing `quad_type:` to `1`
- changing `gui:` to `True` 
- commenting/removing everything after `normalized_rl_action_space` in the `quadrotor_config` part of `verbose_api.yaml` 
- commenting/removing all the printouts from `verbose_api.py`

However, you are right in saying there is a problem: at line 111 of `quadrotor.py`:
```
info_mse_metric_state_weight=[1,0,1,0,0,0],
```
This default only works for the (6 states of the) 2D quad, it should take value `info_mse_metric_state_weight=[1,0]` for the 1D case (whose state is only [z, z_dot]). I will fix this with an additional if-else ASAP.
